# Project information
site_name: Try CONBU
site_description: COnference Network BUilders for FoxBoxsnet
site_author: Naoki Aoyama
site_url: https://about.foxboxsnet.com

# Repository
repo_name: FoxBoxsnet/try-conbu
repo_url: https://github.com/FoxBoxsnet/try-conbu
##edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2018 Naoki Aoyama'

extra_css:
  - 'custom-theme/css/extra.css'
  - 'https://use.fontawesome.com/releases/v5.6.3/css/all.css'

extra_javascript:
  - 'custom-theme/js/extra.js'

# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: ja
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Customization
extra:
  social:
    - type: globe
      link: http://about.foxboxsnet.com
    - type: github-alt
      link: https://github.com/FoxBoxsnet
    - type: twitter
      link: https://twitter.com/FoxBoxsnet

# Extensions
markdown_extensions:
  # 警告文
  - markdown.extensions.admonition
  # コードハイライト
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
    # 定義リスト
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
    # 絵文字
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
    # Keys
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
    # Font Awesome
  - fontawesome_markdown

# Page tree
nav:
  - Home:
      - Home: index.md
      - License: license.md
      - Special Thanks: specialthanks/index.md
      - Contributing: contributing/index.md
  - Commons:
      - Commons: commons/commons-overview.md
      - Public NTP Server: commons/commons-public_ntp.md
      - Syslog facility: commons/commons-syslog-facility.md
  - Networks:
      - ネットワーク: networks/overview.md
      - VPN:
          - IX:
              - 設定: networks/vpn/ix/ix-settings.md
              - 雑記: networks/vpn/ix/ix-miscellaneous_notes.md
          - pfSesne:
              - 概要: networks/vpn/pfsense/pfsense-overview.md
              - 設定: networks/vpn/pfsense/pfsense-settings.md
              - 雑記: networks/vpn/pfsense/pfsense-miscellaneous_notes.md

# Plugins
plugins:
  # https://github.com/byrnereese/mkdocs-minify-plugin
  - minify

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ['GOOGLE_ANALYTICS_KEY']
  - auto
